# Generated by Django 4.1.5 on 2023-01-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(default=0),
        ),
    ]
